    {!! Html::script('/bower/jquery/dist/jquery.min.js') !!}
    {!! Html::script('/bower/boostrap/dist/js/bootstrap.min.js') !!}
    {!! Html::script('/bower/bootbox/bootbox.min.js') !!}
    {!! Html::script('/bower/bootstrap-tagsinput-latest/dist/bootstrap-tagsinput.min.js') !!}
    {!! Html::script('/bower/boostrap/dist/js/app.min.js') !!}
    {!! Html::script('/bower/jquery-validation-1.17.0/dist/jquery.validate.min.js') !!}
    {!! Html::script('/bower/jquery-validation-1.17.0/dist/additional-methods.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/jquery-ui/jquery-ui.min.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/dist/js/adminlte.min.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/datatables.net/js/jquery.dataTables.min.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/fastclick/lib/fastclick.js') !!}
    {!! Html::script('/bower/AdminLTE-2.4.3/bower_components/ckeditor/ckeditor.js') !!}
    {!! Html::script('/js/custom-validate-method.js') !!}
